nunalang v0.3.1 draft
nunalang/nuna pull request #7
Opened 2021-03-13 14:24 UTC by pmh-only

2021-03-13 14:26 UTC, pmh-only commented
@AkiaCode 리뷰 부탁드립니당

2021-03-13 14:37 UTC, AkiaCode requested changes

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +(우리의 가상) 누나 언어 v0.3.1
`(우리의 가상) 누나 언어 v0.3.1 `보다 `(우리의 가상) 누나 언어 v0.4` 로 해주시길 바랍니다

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +언어를 실행할때 pointer값은 `0`으로 초기화됩니다.
pointer -> `pointer`

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +### 키워드 예제
키워드 예제는 examples.md로 이동시켜주시길 바랍니다

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +21년 3월 13일 기준 구현체 목록입니다.
21년으로 표시를 하면 0021년인지 2100년인지 2021년인지 알 수 있는 방법이 없으므로 2021년으로 수정해주시길 바랍니다

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> -##### latest release
이건 왜 지우셨나요?

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +다음 조건을 맞춘 구현체는 이슈로 남겨주시면 nunalang레포로 옮겨드립니다.
nunalang레포로 -> [nunalang/nuna](https://github.com/nunalang/nuna) 레포로

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +* 명세를 최대한 따릅니다.
최대한 보다 무조건으로 수정해주시길 바랍니다

2021-03-13 14:37 UTC, AkiaCode commented on README.md
> +### 공식 구현체 만족 조건
따로 이슈를 파서  거기서 만족 조건을 보여주고 받는 건 어떤가요?

2021-03-13 14:47 UTC, pmh-only commented on README.md
> +다음 조건을 맞춘 구현체는 이슈로 남겨주시면 nunalang레포로 옮겨드립니다.
아 nunalang org로 옮겨준다는 의미였는데...

2021-03-13 14:48 UTC, pmh-only commented on README.md
> +* 명세를 최대한 따릅니다.
언어마다 특성들이 다 있어서 무조건 만족은 힘들꺼 같습니다

2021-03-13 14:51 UTC, AkiaCode commented on README.md
> +다음 조건을 맞춘 구현체는 이슈로 남겨주시면 nunalang레포로 옮겨드립니다.
아하

2021-03-13 14:52 UTC, AkiaCode commented on README.md
> +* 명세를 최대한 따릅니다.
그러면 구현체마다 특성이 다르기 때문에 혼란이 생길 거 같습니다

2021-03-13 15:00 UTC, pmh-only commented on README.md
> +* 명세를 최대한 따릅니다.
혼란보다는 구현이 가능한가 말하는겁니다

2021-03-13 15:01 UTC, pmh-only commented on README.md
> +* 명세를 최대한 따릅니다.
무조건적으로 따라야 한다면 JS로 구현시 Number타입을 버리고 Integer타입을 새로 만들어야 할지도 모릅니다.

2021-03-13 15:01 UTC, AkiaCode commented on README.md
> +* 명세를 최대한 따릅니다.
구현이 가능한가는 명세 쪽에서 생각할 필요가 없을 거라고 생각합니다

2021-03-13 15:04 UTC, AkiaCode commented on README.md
> +* 명세를 최대한 따릅니다.
> 무조건적으로 따라야 한다면 JS로 구현시 Number타입을 버리고 Integer타입을 새로 만들어야 할지도 모릅니다.

그렇군요. 근데 저가 생각하는 건 명세에서 몇 개는 구현하지 않는 다라는 생각이었습니다

2021-03-13 15:06 UTC, AkiaCode commented on README.md
> +## 릴리즈 목록 (releases)
릴리즈 목록은 맨 아래에 있으면 좋을 거 같습니다

2021-03-13 15:07 UTC, AkiaCode commented on README.md
> +| tag | status | released at | author | main commit |
author 보단 기여자들을 서술하는 것이 좋을 거 같습니다

2021-03-13 15:11 UTC, AkiaCode commented on README.md
> +### 공식 구현체 만족 조건
#8

2021-03-13 15:12 UTC, AkiaCode commented on README.md
> +## 릴리즈 목록 (releases)
58dae06

2021-03-13 15:16 UTC, AkiaCode commented on README.md
> +| tag | status | released at | author | main commit |
9686df4

2021-03-14 08:18 UTC, AkiaCode requested changes

2021-03-14 08:18 UTC, AkiaCode commented on README.md
> +시스템 변수를 제외한 모든 변수는 이 스택에 저장됩니다.\
시스템 변수라는 용어는 독자들이 무슨 의미인지 헷갈릴 거 같아서 더 적절하게 수정 해야 할 거 같습니다

2021-03-14 08:18 UTC, AkiaCode commented on README.md
> +* [pl-Steve28-lq/PyNuna](https://github.com/pl-Steve28-lq/PyNuna) - [비공식] Nuna Language Interpreter Implemented with Python
왜 이것만 영어로 표시를 하나요?

2021-03-14 08:18 UTC, AkiaCode commented
이 리뷰만 거치면 머지 됩니다

2021-03-17 12:35 UTC, AkiaCode commented
@pmh-only 
![image](https://user-images.githubusercontent.com/71239005/111468183-9f116d00-8768-11eb-8098-3a97420c0936.png)

이거 수정만 해주신다면 됩니

2021-03-17 12:45 UTC, AkiaCode approved these changes
LGTM

2021-03-17 12:46 UTC, merged